import { afterEach, describe, expect, test } from "bun:test";
import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";

const SCRIPT_PATH = path.join(import.meta.dirname, "inject-references.ts");

function createTmpSkill(): string {
  const dir = path.join(
    tmpdir(),
    `inject-ref-test-${Date.now()}-${Math.random().toString(36).slice(2)}`,
  );
  mkdirSync(dir, { recursive: true });
  return dir;
}

function run(skillDir: string): {
  stdout: string;
  stderr: string;
  exitCode: number;
} {
  const result = Bun.spawnSync([SCRIPT_PATH, skillDir], {
    stdout: "pipe",
    stderr: "pipe",
  });
  return {
    stdout: result.stdout.toString(),
    stderr: result.stderr.toString(),
    exitCode: result.exitCode,
  };
}

const tmpDirs: string[] = [];

afterEach(() => {
  for (const dir of tmpDirs) {
    rmSync(dir, { recursive: true, force: true });
  }
  tmpDirs.length = 0;
});

describe("inject-references", () => {
  test("excludes .test.ts files from scripts/", () => {
    const dir = createTmpSkill();
    tmpDirs.push(dir);

    writeFileSync(
      path.join(dir, "SKILL.md"),
      "---\nname: test-skill\ndescription: test\n---\n\n# Test\n",
    );
    mkdirSync(path.join(dir, "scripts"));
    writeFileSync(
      path.join(dir, "scripts", "run.ts"),
      '#!/usr/bin/env bun\n/**\n * Run something.\n */\nconsole.log("hi");\n',
    );
    writeFileSync(
      path.join(dir, "scripts", "run.test.ts"),
      'import { test } from "bun:test";\ntest("x", () => {});\n',
    );

    const { stdout, exitCode } = run(dir);
    expect(exitCode).toBe(0);

    const result = JSON.parse(stdout);
    expect(result.entries).toBe(1);

    const skillMd = readFileSync(path.join(dir, "SKILL.md"), "utf-8");
    expect(skillMd).toContain("scripts/run.ts");
    expect(skillMd).not.toContain("run.test.ts");
  });

  test("excludes .spec.ts files from scripts/", () => {
    const dir = createTmpSkill();
    tmpDirs.push(dir);

    writeFileSync(
      path.join(dir, "SKILL.md"),
      "---\nname: test-skill\ndescription: test\n---\n\n# Test\n",
    );
    mkdirSync(path.join(dir, "scripts"));
    writeFileSync(
      path.join(dir, "scripts", "validate.ts"),
      "#!/usr/bin/env bun\n/**\n * Validate stuff.\n */\n",
    );
    writeFileSync(path.join(dir, "scripts", "validate.spec.ts"), "// spec\n");

    const { stdout, exitCode } = run(dir);
    expect(exitCode).toBe(0);

    const result = JSON.parse(stdout);
    expect(result.entries).toBe(1);

    const skillMd = readFileSync(path.join(dir, "SKILL.md"), "utf-8");
    expect(skillMd).toContain("scripts/validate.ts");
    expect(skillMd).not.toContain("validate.spec.ts");
  });

  test("requires frontmatter description in references/*.md", () => {
    const dir = createTmpSkill();
    tmpDirs.push(dir);

    writeFileSync(
      path.join(dir, "SKILL.md"),
      "---\nname: test-skill\ndescription: test\n---\n\n# Test\n",
    );
    mkdirSync(path.join(dir, "references"));
    writeFileSync(path.join(dir, "references", "guide.md"), "# No frontmatter\n");

    const { exitCode, stderr } = run(dir);
    expect(exitCode).toBe(1);
    expect(stderr).toContain("missing YAML frontmatter");
  });

  test("injects references with frontmatter description", () => {
    const dir = createTmpSkill();
    tmpDirs.push(dir);

    writeFileSync(
      path.join(dir, "SKILL.md"),
      "---\nname: test-skill\ndescription: test\n---\n\n# Test\n",
    );
    mkdirSync(path.join(dir, "references"));
    writeFileSync(
      path.join(dir, "references", "guide.md"),
      "---\ndescription: A helpful guide\n---\n\n# Guide\n",
    );

    const { stdout, exitCode } = run(dir);
    expect(exitCode).toBe(0);

    const result = JSON.parse(stdout);
    expect(result.entries).toBe(1);
    expect(result.categories).toContain("References");

    const skillMd = readFileSync(path.join(dir, "SKILL.md"), "utf-8");
    expect(skillMd).toContain("A helpful guide");
    expect(skillMd).toContain("REFERENCES_START");
    expect(skillMd).toContain("REFERENCES_END");
  });

  test("updates existing markers without duplicating", () => {
    const dir = createTmpSkill();
    tmpDirs.push(dir);

    const existingContent = [
      "---",
      "name: test-skill",
      "description: test",
      "---",
      "",
      "# Test",
      "",
      "## Bundled Resources",
      "",
      "<!-- REFERENCES_START — AUTO-GENERATED by inject-references.ts — DO NOT EDIT MANUALLY -->",
      "### References",
      "",
      "- **`references/old.md`** (100 B) — Old stuff",
      "<!-- REFERENCES_END -->",
    ].join("\n");

    writeFileSync(path.join(dir, "SKILL.md"), existingContent);
    mkdirSync(path.join(dir, "references"));
    writeFileSync(
      path.join(dir, "references", "new.md"),
      "---\ndescription: New stuff\n---\n\n# New\n",
    );

    const { exitCode } = run(dir);
    expect(exitCode).toBe(0);

    const skillMd = readFileSync(path.join(dir, "SKILL.md"), "utf-8");
    expect(skillMd).toContain("New stuff");
    expect(skillMd).not.toContain("Old stuff");

    const startCount = skillMd.split("REFERENCES_START").length - 1;
    expect(startCount).toBe(1);
  });

  test("empty skill with no resources appends section", () => {
    const dir = createTmpSkill();
    tmpDirs.push(dir);

    writeFileSync(
      path.join(dir, "SKILL.md"),
      "---\nname: test-skill\ndescription: test\n---\n\n# Test\n",
    );

    const { stdout, exitCode } = run(dir);
    expect(exitCode).toBe(0);

    const result = JSON.parse(stdout);
    expect(result.entries).toBe(0);

    const skillMd = readFileSync(path.join(dir, "SKILL.md"), "utf-8");
    expect(skillMd).toContain("No bundled resources found");
  });

  test("fails without skill-dir argument", () => {
    const result = Bun.spawnSync([SCRIPT_PATH], {
      stdout: "pipe",
      stderr: "pipe",
    });
    expect(result.exitCode).toBe(1);
    expect(result.stderr.toString()).toContain("Usage:");
  });

  test("fails when SKILL.md does not exist", () => {
    const dir = createTmpSkill();
    tmpDirs.push(dir);

    const { exitCode, stderr } = run(dir);
    expect(exitCode).toBe(1);
    expect(stderr).toContain("SKILL.md not found");
  });
});
