#!/usr/bin/env bun
/**
 * Scan a skill directory and inject a references section into its SKILL.md.
 *
 * Usage: ./inject-references.ts <skill-dir>
 *
 * Scans scripts/, references/, and assets/ directories.
 * Inserts or updates the list between REFERENCES_START and REFERENCES_END markers.
 * If markers are absent, appends them to the end of SKILL.md.
 */
import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import path from "node:path";

const skillDirArg = process.argv[2];

if (!skillDirArg) {
  process.stderr.write("Usage: ./inject-references.ts <skill-dir>\n");
  process.exit(1);
}

const skillDir: string = skillDirArg;
const skillMdPath = path.join(skillDir, "SKILL.md");
if (!existsSync(skillMdPath)) {
  process.stderr.write(`Error: SKILL.md not found in ${skillDir}\n`);
  process.exit(1);
}

type FileEntry = {
  category: string;
  relativePath: string;
  description: string;
};

/** Extract YAML frontmatter description from a markdown file. */
function extractFrontmatterDescription(content: string): string | null {
  const fmMatch = content.match(/^---\n([\s\S]*?)\n---/);
  if (!fmMatch?.[1]) return null;
  const descMatch = fmMatch[1].match(/^description:\s*["']?(.*?)["']?\s*$/m);
  if (!descMatch?.[1]) return null;
  const desc = descMatch[1].trim();
  return desc.length > 0 ? desc : null;
}

/** Extract description from a script file (JSDoc or first comment). */
function extractScriptDescription(content: string): string {
  const jsdocMatch = content.match(/\/\*\*\s*\n\s*\*\s*(.+)/);
  if (jsdocMatch?.[1]) return jsdocMatch[1].trim();

  const headingMatch = content.match(/^#\s+(.+)$/m);
  if (headingMatch?.[1]) return headingMatch[1].trim();

  return "";
}

/**
 * Extract a description from a file.
 * - references/*.md: YAML frontmatter `description` is REQUIRED (error if missing)
 * - scripts/*: JSDoc / heading / first line (best-effort)
 * - assets/*: best-effort
 */
function extractDescription(filePath: string, relativePath: string, category: string): string {
  try {
    const content = readFileSync(filePath, "utf-8");

    if (category === "References" && filePath.endsWith(".md")) {
      const desc = extractFrontmatterDescription(content);
      if (!desc) {
        process.stderr.write(
          `Error: ${relativePath} is missing YAML frontmatter 'description' field.\n` +
            "References must have frontmatter with a description. Example:\n" +
            "---\n" +
            "description: Short summary of what this reference covers\n" +
            "---\n",
        );
        process.exit(1);
      }
      return desc;
    }

    return extractScriptDescription(content);
  } catch {
    // Fall through
  }
  return "";
}

/** Test file patterns to exclude from scripts/ scanning */
const TEST_PATTERNS = [/\.test\.[cm]?[jt]sx?$/, /\.spec\.[cm]?[jt]sx?$/];

function isTestFile(filename: string): boolean {
  return TEST_PATTERNS.some((p) => p.test(filename));
}

function scanDirectory(dirName: string, category: string): FileEntry[] {
  const dirPath = path.join(skillDir, dirName);
  if (!existsSync(dirPath)) return [];

  const entries: FileEntry[] = [];
  try {
    const files = readdirSync(dirPath).toSorted();
    for (const file of files) {
      if (isTestFile(file)) continue;

      const filePath = path.join(dirPath, file);
      const stat = statSync(filePath);
      if (!stat.isFile()) continue;

      const relPath = `${dirName}/${file}`;
      entries.push({
        category,
        relativePath: relPath,
        description: extractDescription(filePath, relPath, category),
      });
    }
  } catch {
    // Skip unreadable directories
  }
  return entries;
}

// Scan all resource directories
const allEntries = [
  ...scanDirectory("scripts", "Scripts"),
  ...scanDirectory("references", "References"),
  ...scanDirectory("assets", "Assets"),
];

// Generate markdown
function generateMarkdown(entries: FileEntry[]): string {
  if (entries.length === 0) return "(No bundled resources found)";

  const grouped = new Map<string, FileEntry[]>();
  for (const entry of entries) {
    const list = grouped.get(entry.category) ?? [];
    list.push(entry);
    grouped.set(entry.category, list);
  }

  const sections: string[] = [];
  for (const [category, items] of grouped) {
    sections.push(`### ${category}\n`);
    for (const item of items) {
      const desc = item.description ? ` — ${item.description}` : "";
      sections.push(`- **\`${item.relativePath}\`**${desc}`);
    }
    sections.push("");
  }
  return sections.join("\n").trimEnd();
}

const markdown = generateMarkdown(allEntries);

// Read and update SKILL.md
let content = readFileSync(skillMdPath, "utf-8");

const START_MARKER =
  "<!-- REFERENCES_START — AUTO-GENERATED by inject-references.ts — DO NOT EDIT MANUALLY -->";
const END_MARKER = "<!-- REFERENCES_END -->";
const fullSection = `${START_MARKER}\n${markdown}\n${END_MARKER}`;

if (content.includes(START_MARKER) && content.includes(END_MARKER)) {
  // Update existing markers
  content = content.replace(
    new RegExp(`${escapeRegex(START_MARKER)}[\\s\\S]*?${escapeRegex(END_MARKER)}`),
    fullSection,
  );
} else {
  // Append new section
  content = `${content.trimEnd()}\n\n## Bundled Resources\n\n${fullSection}\n`;
}

await Bun.write(skillMdPath, content);

// Output result
const result = {
  updated: skillMdPath,
  entries: allEntries.length,
  categories: [...new Set(allEntries.map((e) => e.category))],
};
process.stdout.write(JSON.stringify(result, null, 2));

function escapeRegex(str: string): string {
  return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
