#!/usr/bin/env bun
/**
 * Fetch frame list from a Figma URL and generate a screen map skeleton.
 * Requires FIGMA_ACCESS_TOKEN.
 */

import { writeFileSync } from "node:fs";
import { defineCommand, runMain } from "citty";
import { env } from "../env.js";

type FigmaNode = {
  id: string;
  name: string;
  type: string;
  children?: FigmaNode[];
};

type FigmaFileResponse = {
  document: FigmaNode;
  name: string;
};

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function isFigmaFileResponse(value: unknown): value is FigmaFileResponse {
  return isRecord(value) && "document" in value && "name" in value;
}

function extractFileKey(url: string): string {
  const match = url.match(/figma\.com\/(?:design|file)\/([a-zA-Z0-9]+)/);
  if (!match?.[1]) {
    throw new Error(
      `Invalid Figma URL: ${url}. Expected format: https://figma.com/design/<file_key>/...`,
    );
  }
  return match[1];
}

function findFrames(node: FigmaNode, pageName?: string): FigmaNode[] {
  const frames: FigmaNode[] = [];

  if (node.type === "CANVAS") {
    if (pageName && node.name !== pageName) {
      return frames;
    }
  }

  if (node.type === "FRAME" && node.children) {
    frames.push(node);
  }

  if (node.children) {
    for (const child of node.children) {
      frames.push(...findFrames(child, node.type === "DOCUMENT" ? pageName : undefined));
    }
  }

  return frames;
}

function nodeIdToUrlFormat(nodeId: string): string {
  return nodeId.replace(/:/g, "-");
}

function generateScreenMap(fileName: string, frames: FigmaNode[]): string {
  const lines: string[] = [];

  lines.push(`# ${fileName} Screen Map`);
  lines.push("");
  lines.push("## Common Rules");
  lines.push("");
  lines.push("- Routing: <!-- Describe routing pattern -->");
  lines.push("- Error display: <!-- Common error display pattern -->");
  lines.push("- Loading: <!-- Common loading pattern -->");
  lines.push("");
  lines.push("## Screen List");
  lines.push("");

  for (let i = 0; i < frames.length; i++) {
    const frame = frames[i];
    if (!frame) continue;
    const num = i + 1;
    const nodeId = nodeIdToUrlFormat(frame.id);

    lines.push(`### ${num}. ${frame.name}`);
    lines.push("");
    lines.push(`- **Figma node-id**: \`${nodeId}\``);
    lines.push("- **Path**: <!-- /path/to/screen -->");
    lines.push("- **States**:");
    lines.push("  - Default: <!-- -->");
    lines.push("  - Loading: <!-- -->");
    lines.push("  - Error: <!-- -->");
    lines.push("  - Success: <!-- -->");
    lines.push("- **Transitions**:");
    lines.push("  - -> <!-- next screen: condition -->");
    lines.push("  - <- <!-- previous screen: condition -->");
    lines.push("- **Validation**: <!-- -->");
    lines.push("- **Notes**: <!-- -->");
    lines.push("");
  }

  lines.push("## Change Log");
  lines.push("");
  const today = new Date().toISOString().slice(0, 10);
  lines.push(`- ${today}: Initial version generated by scaffold`);
  lines.push("");

  return lines.join("\n");
}

const main = defineCommand({
  meta: {
    name: "figma-scaffold",
    description: "Generate a screen map skeleton from a Figma URL",
  },
  args: {
    url: {
      type: "string",
      description: "Figma file URL",
      required: true,
    },
    page: {
      type: "string",
      description: "Page name to filter frames",
      required: false,
    },
    output: {
      type: "string",
      description: "Output file path (default: stdout)",
      required: false,
    },
  },
  async run({ args }) {
    const token = env.FIGMA_ACCESS_TOKEN;
    if (!token) {
      console.error("Error: FIGMA_ACCESS_TOKEN environment variable is required");
      process.exit(1);
    }

    const fileKey = extractFileKey(args.url);
    const apiUrl = `https://api.figma.com/v1/files/${fileKey}?depth=2`;

    const response = await fetch(apiUrl, {
      headers: { "X-Figma-Token": token },
    });

    if (!response.ok) {
      const text = await response.text();
      console.error(`Figma API error ${response.status}: ${text}`);
      process.exit(1);
    }

    const raw: unknown = await response.json();
    if (!isFigmaFileResponse(raw)) {
      console.error("Unexpected Figma API response format");
      process.exit(1);
    }

    const frames = findFrames(raw.document, args.page);

    if (frames.length === 0) {
      console.error(
        args.page ? `No frames found in page "${args.page}"` : "No frames found in the file",
      );
      process.exit(1);
    }

    const markdown = generateScreenMap(raw.name, frames);

    if (args.output) {
      writeFileSync(args.output, markdown, "utf-8");
      console.log(
        JSON.stringify({
          success: true,
          output: args.output,
          frameCount: frames.length,
        }),
      );
    } else {
      console.log(markdown);
    }
  },
});

runMain(main);
